# This formula is GENERATED by lemonfiber/lemonfiber's release CI (cargo-dist).
# Do not edit by hand — a change to the generator is a `cli` change (REPO-R28).
# Placeholder until the first release.
class Lemonfiber < Formula
  desc "Self-hosted media automation stack, run in slices"
  homepage "https://github.com/lemonfiber/lemonfiber"
  version "0.0.0"
  # url / sha256 / bottles are filled in by the release pipeline.

  def install
    bin.install "lemonfiber"
  end

  test do
    assert_match "0.0.0", shell_output("#{bin}/lemonfiber --version")
  end
end
