# This formula is a PLACEHOLDER: the version below is not a released version.
# From 1.0.0 it is GENERATED by lemonfiber/lemonfiber's release CI (cargo-dist),
# which waits on a HOMEBREW_TAP_TOKEN (L1-R3).
# Do not edit by hand — a change to the generator is a `lemonfiber` change
# (REPO-R28).
class Lemonfiber < Formula
  desc "Self-hosted media automation stack, run in slices"
  homepage "https://github.com/lemonfiber/lemonfiber"
  version "0.0.0"
  # url / sha256 / bottles are filled in by the release pipeline.

  def install
    bin.install "lemonfiber"
  end

  test do
    assert_match "0.0.0", shell_output("#{bin}/lemonfiber --version")
  end
end
